# Generated by Django 4.0.5 on 2022-06-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
